### ISSUE TITLE
Meinberg prompt detection

### ISSUE THREAD

**Issue by bewing** [earendilfr/rancid#1]
Howdy -- can you provide an example .cloginrc entry for a Meinberg?  I'm having difficulty with prompt detection that looks like it might be related to color codes in the prompt.

**Comment by earendilfr** [comment]
Hello,

Currently, my .cloginrc configuration for Meinberg is really simple : I 
only connect with a root access with noenable activated:
# For Meinberg appliance
add method <name> {ssh}
add user <name> {root}
add noenable <name> {1}

But I don't use the "clogin" script but a "llogin" that I have wrote to 
connect to different linux host (like Meinberg or Checkpoint devices).
Because clogin doesn't really work well with the linux prompt...

Regards

Le 2017-01-10 15:16, bewing a écrit :
> Howdy -- can you provide an example .cloginrc entry for a Meinberg?
> I'm having difficulty with prompt detection that looks like it might
> be related to color codes in the prompt.

**Comment by earendilfr** [comment]
I hope it's work with the llogin
